name: Docker Scout CLI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scout-cli-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker version

      - name: Download docker scout installer
        run: |
          curl -L https://github.com/docker/scout-cli/releases/latest/download/install.sh -o install.sh
        shell: bash

      - name: Install docker scout
        run: |
          sh ./install.sh
        shell: bash

      - name: Check docker scout version
        run: docker scout version

      - name: Run Docker Scout CLI tests (run_all.ps1)
        shell: pwsh
        run: |
          Set-Location "$env:GITHUB_WORKSPACE"
          powershell -ExecutionPolicy Bypass -File .\tests\run_all.ps1
